const state={topics:[],sources:[],digest:null,region:'全部',query:'',sort:'score',selected:null,draft:null};
const $=s=>document.querySelector(s);
const fmt=d=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
async function loadData(){try{const [res,digestRes]=await Promise.all([fetch(`data/topics.json?t=${Date.now()}`),fetch(`data/weekly-report.json?t=${Date.now()}`)]);if(!res.ok)throw new Error();const data=await res.json();state.topics=data.topics;state.sources=data.sources;state.digest=digestRes.ok?await digestRes.json():null;state.selected=state.topics[0]?.id;$('#lastUpdated').textContent=`${fmt(data.generatedAt)} 更新`;render();}catch{$('#systemStatus').textContent='读取失败';$('#topicList').innerHTML='<div class="empty">暂时无法读取选题数据，请稍后刷新。</div>';}}
function filtered(){return state.topics.filter(t=>(state.region==='全部'||t.region===state.region)&&(`${t.topic}${t.angle}${t.keywords.join('')}`.toLowerCase().includes(state.query))).sort((a,b)=>b[state.sort]-a[state.sort]);}
function render(){renderMetrics();renderFilters();renderTopics();renderDetail();renderSources();renderReport();renderDigest();renderNewsTopics();renderWriterOptions();}
function renderMetrics(){const hot=state.topics.filter(t=>t.score>=80).length,verified=state.topics.filter(t=>t.verified).length,avg=Math.round(state.topics.reduce((n,t)=>n+t.score,0)/(state.topics.length||1));$('#metrics').innerHTML=[['今日候选',state.topics.length,'跨平台聚合'],['高潜选题',hot,'评分 ≥ 80'],['已核实',verified,'保留原始来源'],['平均潜力',avg,'五维模型评分']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('');}
function renderFilters(){const regions=['全部',...new Set(state.topics.map(t=>t.region))];$('#regionFilters').innerHTML=regions.map(r=>`<button class="${r===state.region?'active':''}" data-region="${r}">${r}</button>`).join('');document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{state.region=b.dataset.region;renderFilters();renderTopics();});}
function renderTopics(){const items=filtered();$('#topicCount').textContent=`${items.length} 个候选选题`;$('#topicList').innerHTML=items.length?items.map(t=>`<article class="topic-item ${t.id===state.selected?'active':''}" data-id="${t.id}"><div class="score-ring" style="--score:${t.score}"><b>${t.score}</b></div><div class="topic-copy"><h3>${t.topic}</h3><div class="topic-meta"><span class="tag">${t.region}</span><span class="tag">${t.source}</span>${t.verified?'<span class="tag verified">已核实</span>':'<span class="tag">待复核</span>'}</div></div><span class="trend">${t.trend}</span></article>`).join(''):'<div class="empty">没有符合条件的选题</div>';document.querySelectorAll('.topic-item').forEach(el=>el.onclick=()=>{state.selected=el.dataset.id;renderTopics();renderDetail();});}
function renderDetail(){const t=state.topics.find(x=>x.id===state.selected)||filtered()[0];if(!t){$('#detailPanel').innerHTML='<div class="empty">选择一个选题查看详情</div>';return}const dims=[['热点热度',t.heat],['官号适配',t.relevance],['家长关注',t.anxiety],['信息时效',t.freshness],['本地关联',t.local]];$('#detailPanel').innerHTML=`<div class="detail-top"><div><small>爆款潜力评分</small><div class="big-score">${t.score}<small>/ 100</small></div></div><span class="tag ${t.verified?'verified':''}">${t.verified?'来源已核实':'需要复核'}</span></div><h2>${t.topic}</h2><p class="insight">${t.angle}</p><div class="score-bars">${dims.map(d=>`<div class="bar-row"><span>${d[0]}</span><div class="bar"><i style="width:${d[1]}%"></i></div><b>${d[1]}</b></div>`).join('')}</div><div class="title-box"><label>建议公众号标题</label><p>${t.title}</p><button class="copy-btn" data-copy="${t.title.replaceAll('"','&quot;')}">复制标题</button></div><a class="source-link" href="${t.url}" target="_blank" rel="noreferrer">查看原始来源 ↗</a>`;document.querySelector('[data-copy]').onclick=e=>copy(e.currentTarget.dataset.copy);}
function renderSources(){$('#sourceGrid').innerHTML=state.sources.map(s=>`<article class="source-card"><div class="source-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.description}</p><div class="source-footer"><span>${s.type}</span><b class="ok">${s.status}</b></div></article>`).join('');}
function renderReport(){const picks=[...state.topics].sort((a,b)=>b.score-a.score).slice(0,5);$('#reportDate').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());$('#reportContent').innerHTML=picks.map((t,i)=>`<article class="report-item"><b>TOP ${i+1} · ${t.score}分 · ${t.region}</b><h4>${t.title}</h4><p>${t.angle}</p></article>`).join('');}
function renderDigest(){const d=state.digest;if(!d)return;const verified=d.items.filter(x=>x.status==='官方确认').length;$('#digestSummary').innerHTML=`<div><span>统计区间</span><strong>${d.period}</strong></div><div><span>合格资讯</span><strong>${d.items.length}</strong></div><div><span>官方确认</span><strong>${verified}</strong></div><div><span>申请提醒</span><strong>${d.reminders.length}</strong></div>`;const groups=d.items.reduce((a,x)=>((a[x.region]??=[]).push(x),a),{});$('#digestMain').innerHTML=Object.keys(groups).length?Object.entries(groups).map(([region,items])=>`<section class="digest-country"><h3>${region}</h3>${items.map(x=>`<article class="news-item"><b>${x.title}</b><p>${x.summary}</p><div class="source-meta">${x.status} · ${x.publisher} · ${x.publishedAt} · <a href="${x.url}" target="_blank" rel="noreferrer">查看原文</a></div></article>`).join('')}</section>`).join(''):'<div class="empty">本期尚无通过原文核实的新增资讯。系统不会用旧闻或未经核实内容凑数。</div>';$('#digestSide').innerHTML=`<h3>近期申请与截止提醒</h3>${d.reminders.length?d.reminders.map(x=>`<div class="reminder"><time>${x.date}</time><b>${x.title}</b><p>${x.audience}</p></div>`).join(''):'<p class="empty">暂无已核实提醒</p>'}<div class="coverage-note">${d.coverageNote}</div>`;}
function renderNewsTopics(){const el=$('#newsTopicList');if(!el)return;const verified=state.topics.filter(t=>t.verified);el.innerHTML=verified.length?verified.map(t=>`<article class="news-topic-card"><div><span class="tag verified">${t.region} · 已核实</span><b>${t.topic}</b><p>${t.angle}</p></div><div class="news-topic-action"><strong>${t.score}</strong><span>潜力分</span><button data-open-topic="${t.id}">进入雷达查看</button></div></article>`).join(''):'<div class="empty">当前没有可由已核实资讯转化的选题。资讯更新并核实后会自动出现在这里。</div>';document.querySelectorAll('[data-open-topic]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.openTopic;document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));document.querySelector('[data-view="radar"]').classList.add('active');$('#radarView').classList.add('active');renderTopics();renderDetail();});}
function renderWriterOptions(){const select=$('#writerTopic');if(!select||select.options.length)return;select.innerHTML=state.topics.map(t=>`<option value="${t.id}">${t.title}</option>`).join('');}
function buildDraft(){const t=state.topics.find(x=>x.id===$('#writerTopic').value)||state.topics[0],audience=$('#writerAudience').value.trim()||'准备留学申请的学生及家长',mode=$('#writerMode').value,goal=$('#writerGoal').value.trim();const titles=[t.title,`${t.topic}｜一篇讲清影响、准备与判断边界`,`${t.region}留学准备提醒：哪些人需要关注这件事？`,`别急着跟风：面对${t.topic.replace(/[？?]/g,'')}，先判断这3点`,`${audience}请注意：这份准备清单建议提前保存`];state.draft={t,audience,mode,goal,titles};$('#writerOutput').innerHTML=`<span class="draft-badge">规则草稿 · 发布前需编辑审核</span><h2>${titles[0]}</h2><h3>5组标题与摘要</h3>${titles.map((x,i)=>`<div class="title-option ${i===0?'recommended':''}"><b>${i+1}. ${x}</b><span>${i===0?'信息明确，和现有证据及正文兑现度最高。':'从不同读者情境切入，不增加正文以外的新事实。'}</span></div>`).join('')}<h3>开头</h3><p>每到留学申请的重要节点，学生和家长最担心的往往不是“有没有信息”，而是信息是否准确、是否适用于自己的情况。广州新东方留学结合目前可核实资料，围绕“${t.topic}”梳理值得关注的变化与准备重点。</p><h3>一、先看清这件事影响谁</h3><p>${t.angle} 对于${audience}，建议先确认目标地区、申请阶段和个人条件，再判断是否需要调整当前安排。</p><h3>二、不要只看结论，还要核对适用范围</h3><p>院校要求、签证规则、费用及截止时间都可能因申请年度、项目和个人情况不同而变化。涉及关键决定时，应回到政府、院校或主办方的当前原文，区分已经实施、已公布待生效和仍待确认的信息。</p><h3>三、现在可以做的准备</h3><p>整理目标清单与时间线；核对语言、学术及材料要求；为可能的补充材料预留时间；把尚未确认的问题单独记录并持续更新。${goal?`本篇还需重点落实：${goal}。`:''}</p><h3>结尾</h3><p>留学规划真正重要的，不是追着每一条消息改变方向，而是及时确认哪些变化与自己有关，并把它转化为具体行动。</p><h3>CTA</h3><p>${mode==='conversion'?'如希望进一步梳理个人申请节奏，可通过广州新东方前途出国官网联系顾问，并说明目标院校与当前准备阶段。':'你目前最想进一步了解哪个申请环节？欢迎在留言区告诉我们。'}</p><div class="editor-notes"><b>编辑备注</b><ul><li>采用广州新东方留学机构编辑口吻，不冒充院校或政府官方。</li><li>来源：${t.source}；核实状态：${t.verified?'已有基础核实':'待回查原始来源'}。</li><li>未加入虚构案例、成功率、合作关系、优惠、二维码或自动回复关键词。</li><li>当前为写作方案，扩写至1200—1800字前需补齐具体事实材料。</li></ul></div><div class="writer-actions"><button id="copyDraft">复制方案</button><button id="downloadDraft">下载 Markdown</button></div>`;$('#copyDraft').onclick=()=>copy($('#writerOutput').innerText);$('#downloadDraft').onclick=downloadDraft;}
function copy(text){navigator.clipboard.writeText(text);toast('内容已复制');}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800);}
function download(){const picks=[...state.topics].sort((a,b)=>b.score-a.score).slice(0,10);const md=`# 广州新东方留学｜选题日报\n\n生成时间：${new Date().toLocaleString('zh-CN')}\n\n${picks.map((t,i)=>`## ${i+1}. ${t.title}\n\n- 爆款潜力：${t.score}/100\n- 地区：${t.region}\n- 切入角度：${t.angle}\n- 来源：${t.source}\n- 原文：${t.url}\n`).join('\n')}`;save(md,`留学选题日报-${new Date().toISOString().slice(0,10)}.md`);}
function downloadDraft(){if(!state.draft)return;save(`# ${state.draft.titles[0]}\n\n${$('#writerOutput').innerText}`,`公众号文章方案-${new Date().toISOString().slice(0,10)}.md`);}
function save(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active');});
$('#searchInput').oninput=e=>{state.query=e.target.value.trim().toLowerCase();renderTopics();};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderTopics();};$('#refreshBtn').onclick=()=>{toast('正在更新选题');loadData();};$('#downloadReport').onclick=download;$('#generateDraft').onclick=buildDraft;loadData();
