const state={topics:[],sources:[],region:'全部',query:'',sort:'score',selected:null};
const $=s=>document.querySelector(s);
const fmt=d=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));

async function loadData(){
  try{const res=await fetch(`data/topics.json?t=${Date.now()}`);if(!res.ok)throw new Error();const data=await res.json();state.topics=data.topics;state.sources=data.sources;state.selected=state.topics[0]?.id;$('#lastUpdated').textContent=`${fmt(data.generatedAt)} 更新`;render();}
  catch{$('#systemStatus').textContent='读取失败';$('#topicList').innerHTML='<div class="empty">暂时无法读取选题数据，请稍后刷新。</div>';}
}
function filtered(){return state.topics.filter(t=>(state.region==='全部'||t.region===state.region)&&(`${t.topic}${t.angle}${t.keywords.join('')}`.toLowerCase().includes(state.query))).sort((a,b)=>b[state.sort]-a[state.sort]);}
function render(){renderMetrics();renderFilters();renderTopics();renderDetail();renderSources();renderReport();}
function renderMetrics(){const hot=state.topics.filter(t=>t.score>=80).length;const verified=state.topics.filter(t=>t.verified).length;const avg=Math.round(state.topics.reduce((n,t)=>n+t.score,0)/(state.topics.length||1));$('#metrics').innerHTML=[['今日候选',state.topics.length,'跨平台聚合'],['高潜选题',hot,'评分 ≥ 80'],['已核实',verified,'保留原始来源'],['平均潜力',avg,'五维模型评分']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong><em>${x[2]}</em></div>`).join('');}
function renderFilters(){const regions=['全部',...new Set(state.topics.map(t=>t.region))];$('#regionFilters').innerHTML=regions.map(r=>`<button class="${r===state.region?'active':''}" data-region="${r}">${r}</button>`).join('');document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{state.region=b.dataset.region;renderFilters();renderTopics();});}
function renderTopics(){const items=filtered();$('#topicCount').textContent=`${items.length} 个候选选题`;$('#topicList').innerHTML=items.length?items.map(t=>`<article class="topic-item ${t.id===state.selected?'active':''}" data-id="${t.id}"><div class="score-ring" style="--score:${t.score}"><b>${t.score}</b></div><div class="topic-copy"><h3>${t.topic}</h3><div class="topic-meta"><span class="tag">${t.region}</span><span class="tag">${t.source}</span>${t.verified?'<span class="tag verified">已核实</span>':'<span class="tag">待复核</span>'}</div></div><span class="trend">${t.trend}</span></article>`).join(''):'<div class="empty">没有符合条件的选题</div>';document.querySelectorAll('.topic-item').forEach(el=>el.onclick=()=>{state.selected=el.dataset.id;renderTopics();renderDetail();});}
function renderDetail(){const t=state.topics.find(x=>x.id===state.selected)||filtered()[0];if(!t){$('#detailPanel').innerHTML='<div class="empty">选择一个选题查看详情</div>';return}const dims=[['热点热度',t.heat],['官号适配',t.relevance],['家长关注',t.anxiety],['信息时效',t.freshness],['本地关联',t.local]];$('#detailPanel').innerHTML=`<div class="detail-top"><div><small>爆款潜力评分</small><div class="big-score">${t.score}<small>/ 100</small></div></div><span class="tag ${t.verified?'verified':''}">${t.verified?'来源已核实':'需要复核'}</span></div><h2>${t.topic}</h2><p class="insight">${t.angle}</p><div class="score-bars">${dims.map(d=>`<div class="bar-row"><span>${d[0]}</span><div class="bar"><i style="width:${d[1]}%"></i></div><b>${d[1]}</b></div>`).join('')}</div><div class="title-box"><label>建议公众号标题</label><p>${t.title}</p><button class="copy-btn" data-copy="${t.title.replaceAll('"','&quot;')}">复制标题</button></div><a class="source-link" href="${t.url}" target="_blank" rel="noreferrer">查看原始来源 ↗</a>`;document.querySelector('[data-copy]').onclick=e=>copy(e.currentTarget.dataset.copy);}
function renderSources(){$('#sourceGrid').innerHTML=state.sources.map(s=>`<article class="source-card"><div class="source-icon">${s.icon}</div><h3>${s.name}</h3><p>${s.description}</p><div class="source-footer"><span>${s.type}</span><b class="ok">${s.status}</b></div></article>`).join('');}
function renderReport(){const picks=[...state.topics].sort((a,b)=>b.score-a.score).slice(0,5);$('#reportDate').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());$('#reportContent').innerHTML=picks.map((t,i)=>`<article class="report-item"><b>TOP ${i+1} · ${t.score}分 · ${t.region}</b><h4>${t.title}</h4><p>${t.angle}</p></article>`).join('');}
function copy(text){navigator.clipboard.writeText(text);toast('标题已复制');}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800);}
function download(){const picks=[...state.topics].sort((a,b)=>b.score-a.score).slice(0,10);const md=`# 广州新东方留学｜选题日报\n\n生成时间：${new Date().toLocaleString('zh-CN')}\n\n${picks.map((t,i)=>`## ${i+1}. ${t.title}\n\n- 爆款潜力：${t.score}/100\n- 地区：${t.region}\n- 切入角度：${t.angle}\n- 来源：${t.source}\n- 原文：${t.url}\n`).join('\n')}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([md],{type:'text/markdown'}));a.download=`留学选题日报-${new Date().toISOString().slice(0,10)}.md`;a.click();URL.revokeObjectURL(a.href);}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active');});
$('#searchInput').oninput=e=>{state.query=e.target.value.trim().toLowerCase();renderTopics();};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderTopics();};$('#refreshBtn').onclick=()=>{toast('正在更新选题');loadData();};$('#downloadReport').onclick=download;loadData();
